### ISSUE TITLE
Setup returning an error: "Could not find suitable distribution for Requirement.parse('ueberzug')"

### ISSUE THREAD

**Issue by Minesweeper76** [GuardKenzie/miniplayer#33]
I cannot find any suitable packager for that dependency.
I am running Fedora 37 with Linux kernel 6.0.10

Can someone help me?

**Comment by Minesweeper76** [comment]
> It seems that the maintainer of Überzug has decided to [discontinue the project and removed it from PyPi.](https://github.com/seebye/ueberzug/blob/master/README.md)
> 
> While I search for a suitable replacement, you can work around this by cloning an [older commit of Überzug](https://github.com/seebye/ueberzug/tree/3780b8155e25514eab66d4980d59b9a378d6ec17) and installing manually.
> 
> Hope this helps!

Thanks!
I will try it and let you know

**Comment by GuardKenzie** [comment]
Please don't run miniplayer as root. What happens if you skip the sudo? Also, what is the output of `where miniplayer`.

Make sure you have curses and mpd installed.

Please also post the contents of your mpd config, and the miniplayer config if you have it configured.

**Comment by Minesweeper76** [comment]
Here is the output without sudo:

Traceback (most recent call last):
  File "/usr/local/bin/miniplayer", line 4, in <module>
    __import__('pkg_resources').run_script('miniplayer==1.8.0', 'miniplayer')
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 672, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1479, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.11/site-packages/miniplayer-1.8.0-py3.11.egg/EGG-INFO/scripts/miniplayer", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
PermissionError: [Errno 13] Permission denied:  /usr/local/lib/python3.11/site-packages/pixcat-0.1.4-py3.11.egg/pixcat/__init__.py

here is the output for `where miniplayer`:

`/usr/local/bin/miniplayer`

I did not have mpd installed. After installing I ran the command again but nothing different happened.

Also, the configurations are untouched by me.

**Comment by GuardKenzie** [comment]
It looks like your pixcat installation is broken. Try reinstalling with pip running as user.

If you need further assistance, please open a new issue.
